'use strict';
const $=id=>document.getElementById(id);const els={statusDot:$('statusDot'),statusText:$('statusText'),latency:$('latency'),frameRate:$('frameRate'),agentCount:$('agentCount'),teamCount:$('teamCount'),contactCount:$('contactCount'),nearest:$('nearest'),riskLevel:$('riskLevel'),sourceAge:$('sourceAge'),radar:$('radar'),range:$('range'),rangeLabel:$('rangeLabel'),primaryAlert:$('primaryAlert'),threatList:$('threatList'),teamList:$('teamList'),supplyList:$('supplyList'),eventLog:$('eventLog'),clock:$('clock'),voiceBtn:$('voiceBtn'),demoBtn:$('demoBtn'),clearBtn:$('clearBtn')};
const ctx=els.radar.getContext('2d');const state={self:null,teammates:new Map(),contacts:new Map(),agents:[],voice:true,range:120,frames:[],lastAt:0,lastSpeech:new Map(),events:new Map(),demo:null};
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(num(a.x)-num(b.x),num(a.y)-num(b.y)),bearing=(a,b)=>(Math.atan2(num(b.y)-num(a.y),num(b.x)-num(a.x))*180/Math.PI+360)%360,norm=d=>(d+540)%360-180,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function dir(me,t){const d=norm(bearing(me,t)-num(me.yaw));if(d>=-22.5&&d<22.5)return'正前方';if(d<67.5&&d>=22.5)return'右前方';if(d<112.5&&d>=67.5)return'右侧';if(d<157.5&&d>=112.5)return'右后方';if(d>=157.5||d<-157.5)return'正后方';if(d>=-157.5&&d<-112.5)return'左后方';if(d>=-112.5&&d<-67.5)return'左侧';return'左前方'}
function logEvent(text,level='info',key=''){const t=Date.now();if(key){const p=state.events.get(key)||0;if(t-p<2500)return;state.events.set(key,t)}const r=document.createElement('div');r.className='event '+level;r.innerHTML=`<span>[${new Date().toLocaleTimeString('zh-CN',{hour12:false})}]</span> <b>${esc(text)}</b>`;els.eventLog.prepend(r);while(els.eventLog.children.length>100)els.eventLog.lastChild.remove()}
function speak(text,key,cool=5000){if(!state.voice||!speechSynthesis)return;const t=Date.now(),p=state.lastSpeech.get(key)||0;if(t-p<cool)return;state.lastSpeech.set(key,t);const u=new SpeechSynthesisUtterance(text);u.lang='zh-CN';u.rate=1.15;speechSynthesis.speak(u)}
function setStatus(kind,text){els.statusDot.className='dot '+kind;els.statusText.textContent=text}
function ingest(p){if(!p||typeof p!=='object')return;state.self=p.self||null;state.teammates=new Map((p.teammates||[]).map(x=>[String(x.id),x]));state.contacts=new Map((p.contacts||[]).map(x=>[String(x.id),x]));state.agents=p.agents||[];state.lastAt=Date.now();state.frames.push(state.lastAt);state.frames=state.frames.filter(t=>state.lastAt-t<1000);if(p.event?.text)logEvent(p.event.text,p.event.level||'info','hub:'+p.event.text);analyze();render()}
function threat(e){if(!state.self)return{score:0,distance:Infinity,direction:'--'};const d=dist(state.self,e),confidence=e.confidence==null?1:clamp(num(e.confidence),0,1),score=clamp((1-d/120)*.75+confidence*.25,0,1);return{score,distance:d,direction:dir(state.self,e)}}
function armorPct(e){const a=e?.equipment?.armorDurability,m=e?.equipment?.armorMax;return a!=null&&m?clamp(a/m*100,0,100):null}
function equipmentText(e){const q=e?.equipment||{},a=[];if(q.primary)a.push(q.primary);if(q.ammoType)a.push(q.ammoType);if(q.armor)a.push(q.armor);const p=armorPct(e);if(p!=null)a.push(`甲${p.toFixed(0)}%`);if(q.helmet)a.push(q.helmet);return a.length?a.join(' · '):'装备未知'}
function supplyText(e){const s=e?.supplies||{},a=[];if(s.ammo!=null)a.push(`弹${s.ammo}`);if(s.medkits!=null)a.push(`医疗${s.medkits}`);if(s.armorRepair!=null)a.push(`修甲${s.armorRepair}`);if(s.grenades!=null)a.push(`雷${s.grenades}`);if(s.smoke!=null)a.push(`烟${s.smoke}`);return a.length?a.join(' · '):'补给未知'}
function analyze(){const ts=[...state.contacts.values()].map(e=>({e,...threat(e)})).sort((a,b)=>b.score-a.score),top=ts[0];if(top){els.nearest.textContent=Math.round(Math.min(...ts.map(x=>x.distance)))+'m';els.riskLevel.textContent=top.score>=.75?'极高':top.score>=.55?'高':top.score>=.32?'警戒':'低';if(top.score>=.55){const msg=`${top.direction} ${Math.round(top.distance)}米，高威胁`;els.primaryAlert.textContent=msg;els.primaryAlert.classList.remove('hidden');speak(msg,'threat:'+top.e.id,4000)}}else{els.nearest.textContent='--';els.riskLevel.textContent='安全';els.primaryAlert.classList.add('hidden')}for(const m of state.teammates.values()){const s=m.supplies||{},ap=armorPct(m);if(s.ammo!=null&&s.ammo<30)logEvent(`${m.name||m.id} 弹药偏低，仅剩 ${s.ammo}`,'warn','ammo:'+m.id);if(s.medkits===0)logEvent(`${m.name||m.id} 医疗耗尽`,'warn','med:'+m.id);if(ap!=null&&ap<25)logEvent(`${m.name||m.id} 护甲低于四分之一`,'warn','armor:'+m.id)}}
function render(){const ts=[...state.contacts.values()].map(e=>({e,...threat(e)})).sort((a,b)=>b.score-a.score);els.agentCount.textContent=state.agents.filter(a=>a.online).length;els.teamCount.textContent=state.teammates.size;els.contactCount.textContent=state.contacts.size;els.frameRate.textContent=state.frames.length+' Hz';els.latency.textContent=state.lastAt?Math.max(0,Date.now()-state.lastAt)+' ms':'-- ms';els.sourceAge.textContent=state.lastAt?Math.max(0,Date.now()-state.lastAt)+'ms':'--';if(!ts.length){els.threatList.className='list empty';els.threatList.textContent='当前无已知目标'}else{els.threatList.className='list';els.threatList.innerHTML=ts.slice(0,12).map(x=>{const c=x.score>=.6?'high':x.score>=.3?'mid':'low';return`<div class="card"><div class="name">${esc(x.e.name||x.e.id)}</div><div class="meta">${x.direction} · ${x.distance.toFixed(0)}m · ${esc(x.e.source||'unknown')}</div><div class="meta intel">${esc(equipmentText(x.e))}</div><div class="meta">${esc(supplyText(x.e))}</div><div class="score ${c}">${Math.round(x.score*100)}</div></div>`}).join('')}const mates=[...state.teammates.values()];if(!mates.length){els.teamList.className='list empty';els.teamList.textContent='当前无队友数据'}else{els.teamList.className='list';els.teamList.innerHTML=mates.map(m=>{const d=state.self?dist(state.self,m):0,c=m.downed||d>70?'high':d>45?'mid':'low';return`<div class="card"><div class="name">${esc(m.name||m.id)}</div><div class="meta">${esc(m.downed?'倒地':m.action||'在线')} · ${d.toFixed(0)}m · ${state.self?dir(state.self,m):'--'}</div><div class="meta intel">${esc(equipmentText(m))}</div><div class="meta">${esc(supplyText(m))}</div><div class="score ${c}">${d.toFixed(0)}m</div></div>`}).join('')}const members=[state.self,...mates].filter(Boolean);els.supplyList.className=members.length?'supply-grid':'supply-grid empty';els.supplyList.innerHTML=members.length?members.map((m,i)=>{const ap=armorPct(m),hp=m.hp==null?'--':`${Math.round(m.hp)}${m.maxHp?'/'+Math.round(m.maxHp):''}`;return`<div class="supply-card"><div class="supply-head"><b>${esc(i===0?'我':m.name||m.id)}</b><span>${esc(m.action||'')}</span></div><div class="supply-line"><span>主武器</span><strong>${esc(m.equipment?.primary||'--')}</strong></div><div class="supply-line"><span>弹种</span><strong>${esc(m.equipment?.ammoType||'--')}</strong></div><div class="supply-line"><span>生命 / 护甲</span><strong>${hp} / ${ap==null?'--':ap.toFixed(0)+'%'}</strong></div><div class="supply-line"><span>剩余补给</span><strong>${esc(supplyText(m))}</strong></div></div>`}).join(''):'等待队伍装备与补给数据'}
function resize(){const r=els.radar.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=Math.floor(r.width*dpr),h=Math.floor(r.height*dpr);if(els.radar.width!==w||els.radar.height!==h){els.radar.width=w;els.radar.height=h}ctx.setTransform(dpr,0,0,dpr,0,0)}
function draw(){resize();const w=els.radar.clientWidth,h=els.radar.clientHeight,cx=w/2,cy=h/2;ctx.clearRect(0,0,w,h);const mr=Math.min(w,h)*.44;ctx.strokeStyle='rgba(77,227,255,.13)';for(let i=1;i<=4;i++){ctx.beginPath();ctx.arc(cx,cy,mr*i/4,0,Math.PI*2);ctx.stroke()}ctx.beginPath();ctx.moveTo(cx,cy-mr);ctx.lineTo(cx,cy+mr);ctx.moveTo(cx-mr,cy);ctx.lineTo(cx+mr,cy);ctx.stroke();const me=state.self||{x:0,y:0,yaw:0},to=e=>{const dx=e.x-me.x,dy=e.y-me.y,a=-num(me.yaw)*Math.PI/180,rx=dx*Math.cos(a)-dy*Math.sin(a),ry=dx*Math.sin(a)+dy*Math.cos(a),s=mr/state.range;return[cx+rx*s,cy-ry*s]},ent=(e,color,label,r=5)=>{const[x,y]=to(e);if(Math.hypot(x-cx,y-cy)>mr+12)return;ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.font='10px system-ui';ctx.fillStyle='#d9e9f3';ctx.fillText(label,x+8,y+3)};for(const m of state.teammates.values())ent(m,m.downed?'#ff5c6c':'#4cf0a6',m.name||m.id);for(const e of state.contacts.values()){const t=threat(e);ent(e,'#ff5c6c',`${e.name||e.id} ${Math.round(t.distance)}m${e.equipment?.primary?' · '+e.equipment.primary:''}`,5+t.score*3)}ctx.fillStyle='#4de3ff';ctx.beginPath();ctx.moveTo(cx,cy-10);ctx.lineTo(cx+7,cy+8);ctx.lineTo(cx,cy+5);ctx.lineTo(cx-7,cy+8);ctx.closePath();ctx.fill();requestAnimationFrame(draw)}
function connect(){if(state.demo)return;const es=new EventSource('./events');es.onopen=()=>setStatus('live','Hub 实时连接');es.onerror=()=>setStatus('error','Hub 连接中断，自动重连');es.onmessage=e=>{try{ingest(JSON.parse(e.data))}catch{}}}
function demo(){if(state.demo){clearInterval(state.demo);state.demo=null;els.demoBtn.textContent='本地 Demo';connect();return}els.demoBtn.textContent='停止 Demo';let t=0;state.demo=setInterval(()=>{t+=.1;ingest({ts:Date.now(),agents:[{agent_id:'a',online:true},{agent_id:'b',online:true}],self:{id:'me',name:'我',x:100,y:100,yaw:(t*5)%360,hp:86,maxHp:100,equipment:{primary:'M4A1',ammoType:'5.56 AP',armor:'战术甲',armorDurability:72,armorMax:100},supplies:{ammo:118,medkits:2,armorRepair:1,grenades:1,smoke:2}},teammates:[{id:'T2',name:'二号',x:120+Math.sin(t)*5,y:108,action:'前压',equipment:{primary:'K416',armor:'重甲',armorDurability:58,armorMax:100},supplies:{ammo:64,medkits:1,smoke:1}},{id:'T3',name:'三号',x:85,y:128,action:'架枪',equipment:{primary:'SR-25',armor:'轻甲',armorDurability:90,armorMax:100},supplies:{ammo:42,medkits:2,smoke:2}}],contacts:[{id:'E1',name:'目标A',x:150-(t%12)*2,y:110,confidence:.92,source:'visual',equipment:{primary:'SCAR-H',armor:'重甲',armorDurability:80,armorMax:100},supplies:{ammo:90}}]})},100)}
els.voiceBtn.onclick=()=>{state.voice=!state.voice;els.voiceBtn.textContent='语音：'+(state.voice?'开':'关');if(!state.voice)speechSynthesis.cancel()};els.demoBtn.onclick=demo;els.clearBtn.onclick=()=>els.eventLog.innerHTML='';els.range.oninput=()=>{state.range=num(els.range.value,120);els.rangeLabel.textContent=state.range+'m'};setInterval(()=>{els.clock.textContent=new Date().toLocaleTimeString('zh-CN',{hour12:false});render()},500);connect();draw();render();
